### ISSUE TITLE
Same user can't login from 2 computer at a time

### ISSUE THREAD

**Issue by ulshamim** [redooor/redminportal#181]
Hi I am using laravel 4.2, I can't login with same user details from 2 device at a time. Only 1 can be logged in. Can you please share me some code which will give user to access same user from both device.

**Comment by kongnir** [comment]
Hi, for L4.2, we're using Cartalyst's Sentry package for authentication. To enable multiple logins, you may need to change the source of Sentry. Take a look at http://stackoverflow.com/a/17399735

**Comment by kongnir** [comment]
This method is probably better http://stackoverflow.com/a/23394423

**Comment by ulshamim** [comment]
Hi It's still not working . I followed this url: http://stackoverflow.com/questions/17393833/laravel-enable-sentry-user-account-be-used-in-multiple-computers/17399735#17399735 but it's not working. Please help me.

**Comment by kongnir** [comment]
Hi, I've tried that quite long ago. Follow the one from Gravy instead.
http://stackoverflow.com/a/23394423

Create a User.php model with this content:
```
use Cartalyst\Sentry\Users\Eloquent\User as SentryUser;

class User extends SentryUser
{
    // Override the SentryUser getPersistCode method.

    public function getPersistCode()
    {
        if (!$this->persist_code)
        {
            $this->persist_code = $this->getRandomString();

            // Our code got hashed
            $persistCode = $this->persist_code;

            $this->save();

            return $persistCode;
        }
        return $this->persist_code;
    }
}
```

Then you need to publish the config file of Sentry with this command:
```
php artisan config:publish cartalyst/sentry
```
It should create a file in app/config/packages/cartalyst/sentry/config.php.

In that file, replace
```
'model' => 'Cartalyst\Sentry\Users\Eloquent\User',
```

with
```
'model' => 'User',
```
