### ISSUE TITLE
Product images not displaying ?

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [redooor/redminportal#189]
How can i display product images in front end  ??? below is my code but it's not displaying ?
 @foreach($product->images as $image)
        {{dd($image->path)}}
@endforeach

**Comment by kongnir** [comment]
Hi, did you check if the image are attached to the product?

Will this give you anything?
```php
@foreach ($product->images as $image)
{{ var_dump($image) }}
@endforeach
```

The images should be stored in the location specified in src/config/image.php.
By default it's at "public/assets/img".

To get the full URL, you can use the helper function:

```php
use Redooor\Redminportal\App\Classes\Imagine;

$imagine = new Imagine;

foreach ($product->images as $image) {
$imagine->getUrl($image->path)
}
```

**Comment by ZaheerAbbasAghani** [comment]
I want to integrate your dashboard with my own created html template and  i want to display images in view called frontend.blade.php when i use below code 

@foreach ($product->images as $image)
{{ var_dump($image) }}
@endforeach

it is giving me an error 

Trying to get property of non-object (View: C:\laragon\www\myproject\resources\views\welcome.blade.php)

and i am also unable to get full Url of image.
And i also created a new model to display data in frontend with same name.

**Comment by ZaheerAbbasAghani** [comment]
And can't display categories image. with above code where i am fetching data from category table.
Controller
 $sub_categories = DB::table('categories')->whereNotNull('category_id')->orderBy('name')->paginate(20);

View

   <?php foreach($sub_categories as $category ): ?>
                <div class="grid-item">
                    <div class="banner-style">
                    
                    @foreach($category->images as $image)
                        <a href="/category/{{ $category->id }}">
                            <img src="{{$image->path}}" alt="" />
                            <span class="text"> 
                                <span class="text1">
                                    <span><?php echo $category->name; ?></span>
                                </span> 
                                <span class="text2">shop now</span> 
                            </span>                         
                        </a>
                      @endforeach
                    </div>
                </div>
            <?php endforeach; ?>
                </div>

**Comment by kongnir** [comment]
Hi,

You're using the model wrongly, that's why you can't get the images.
In order to use the Eloquent model, you need to call the model directly.

To get Category, you should do this instead:
```php
use Redooor\Redminportal\Models\Category;

$sub_categories = Category::whereNotNull('category_id')->orderBy('name')->paginate(20);
```

Notice I didn't use DB::Table('categories') because all the properties won't be available if you use DB class. You have to use Category class.

As for the layout of images, it's up to you to develop the frontend code to display them. You could use a list to hide all but first image with CSS, and then use Javascript to display one at a time when user click the next button.

**Comment by ZaheerAbbasAghani** [comment]
Great.
and how can i show first image as i add multiple images to product  in frontend??? image share above.

**Comment by kongnir** [comment]
Hi,

You can do all things Eloquent to the model.

```php
$product = Product::find($some_id);

// Get first image of the product, it'll return null if no image found
$first_image = $product->images()->first();

// You can even get certain number of images like this
$get_3_images = $product->images()->get(3);
```

**Comment by ZaheerAbbasAghani** [comment]
I had created bundle products and want to show bundle products image with below code but getting Null resutl... help needed.?
  $bundle = Bundle::find($id)->first();
       //dd($bundle);
       $first_image = $bundle->images()->first();
     dd($first_image);

**Comment by kongnir** [comment]
Hi @ZaheerAbbasAghani , you probably need to explore more about Laravel framework first before attempting to use this package.

Bundle::find($id) will give you the object if the ID is found. You don't need to use first() on it.

`Bundle::find($id);`

Is the same as

`Bundle::where('id', $id)->first();`
