### ISSUE TITLE
How can we upgrade laravel 5.5

### ISSUE THREAD

**Issue by usman101** [redooor/redminportal#190]
Hey 

I like your application, I am also working on extension over this application. Would you please let me know how can we upgrade laravel version to latest 5.5 lts?

**Comment by kongnir** [comment]
Hi @usman101 , I had attempted to upgrade to v5.2 but didn't have time for it. There're some functionally changes in 5.2 onwards that need quite some effort. You could fork this project and do make the changes and submit a pull request. I'll be happy to look through it. :)

**Comment by kongnir** [comment]
@usman101 also, I had begin some work on branch dev to support v5.2. Maybe you wanna look at that branch and see if we can upgrade to 5.5?

**Comment by kongnir** [comment]
Please see issue #175 . Gonna jump to support version 5.5 instead of 5.2.
