### ISSUE TITLE
error occurs when create new category

### ISSUE THREAD

**Issue by feryonline** [redooor/redminportal#37]
I'm sorry for my bad english! 

when i try to create new category this error occurs:

Illuminate \ Database \ QueryException (23000)

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel42_redminportal`.`categories`, CONSTRAINT `categories_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)) (SQL: insert into `categories` (`name`, `short_description`, `long_description`, `active`, `order`, `options`, `category_id`, `updated_at`, `created_at`) values (My Category, Test cat, Test Category, 1, 0, {"name":null,"short_description":null,"long_description":null}, 0, 2014-12-26 16:02:38, 2014-12-26 16:02:38))

**Comment by kongnir** [comment]
Hi @feryonline, moltin/laravel-cart looks abandoned, the last update was 7 months ago. Crinsane/LaravelShoppingcart looks promising, but note that RedminPortal is still using Laravel 4.2, so you should try Crinsane/LaravelShoppingcart v1.2 instead. Laravel 5 is still under development. We'll probably upgrade to it when it's officially released.

**Comment by feryonline** [comment]
Thank you very much @kongnir
