### ISSUE TITLE
Image of Products does not exist

### ISSUE THREAD

**Issue by feryonline** [redooor/redminportal#39]
Dear @kongnir , Sorry for bothering you!

I've added an image for each products, but when I reviewed products that image does not appear in the uploaded image section. also I've checked the products table in database and the "2013_06_17_060056_create_products_table.php" migration file but doesn't exist any column for the images!

**Comment by kongnir** [comment]
Hi @feryonline, is there an "Image" table in the database? The migration file for image table is 
```
2013_06_17_061525_create_images_table.php
```

I just checked and it's working on my workstation.

We're using the plugin "Imagine" (https://github.com/avalanche123/Imagine) for cropping and resizing the images. Make sure you have installed and enabled PHP extension for GD2. http://php.net/manual/en/image.installation.php

Also, if you're installing RedminPortal via composer, remember to run
```
php artisan config:publish redooor/redminportal
```
This command will add 3 files to folder app/config/packages/redooor/redminportal:
* image.php <-- This is important
* menu.php
* translation.php

**Comment by feryonline** [comment]
Hi @kongnir , I have installed and enabled PHP extension for GD2:
-------------------------------------------------------------------------------
GD Support 	enabled
GD Version 	bundled (2.1.0 compatible)
FreeType Support 	enabled
FreeType Linkage 	with freetype
FreeType Version 	2.5.3
GIF Read Support 	enabled
GIF Create Support 	enabled
JPEG Support 	enabled
libJPEG Version 	9 compatible
PNG Support 	enabled
libPNG Version 	1.5.18
WBMP Support 	enabled
XPM Support 	enabled
libXpm Version 	30411
XBM Support 	enabled
WebP Support 	enabled 
-------------------------------------
            Directive                           	Local Value	Master Value
gd.jpeg_ignore_warning          	        0              	  0
---------------------------------------------------------------------------------

Images of Products are exist in "Image" table in the database, also are exist in the "assets\img\products" folder, but Is shown as a broken image in the "Uploaded Photos" section at the product's edit page!, and when I go to the direct image URL via the image properties, like this: "http://localhost:8000/assets/img/products/1406OgVlpIWsSXQYutj1MpI.jpg" I get this error:
----------------------------------------------------------------------
Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException

Open: C:\xampp\htdocs\laravel42-redminportal\bootstrap\compiled.php

    if (!is_null($route)) {
    return $route->bind($request);
    }
    $others = $this->checkForAlternateVerbs($request);
    if (count($others) > 0) {
    return $this->getOtherMethodsRoute($request, $others);
    }
    throw new NotFoundHttpException();
    }
    protected function checkForAlternateVerbs($request)
---------------------------------------------------------------------------

Also I've run this command during installation:  php artisan config:publish redooor/redminportal
These 3 files there are in this folder "app/config/packages/redooor/redminportal" folder:
    image.php
    menu.php
    translation.php

you can check the screenshot of my problem: http://i58.tinypic.com/nbtend.jpg

**Comment by kongnir** [comment]
Hi @feryonline , this seems like a routing issue on your installation. The public path may have been set wrongly.

Is your http://localhost:8000 pointing to the "public" folder of Laravel installation?
Can you try echoing these on your welcome page and tell me what you see?

```
<?php echo app_path(); ?>
<?php echo base_path(); ?>
<?php echo public_path(); ?>
<?php echo asset("assets/img/products/1406OgVlpIWsSXQYutj1MpI.jpg"); ?>
```
http://laravel.com/docs/4.2/helpers#paths

Find this file /bootstrap/paths.php, you should change the "public" variable to the full path of your installation.

**Comment by feryonline** [comment]
Hi @kongnir , this issue is related with the location of the assets folder.
Because the assets folder is located at the outside of the public folder! 

My public folder is there: C:\xampp\htdocs\laravel42-redminportal\public
But assets folder is there: C:\xampp\htdocs\laravel42-redminportal\assets

When I moved assets folder to the public folder everything is Ok, 
But when I add new products, all the images of new products placed outside the public folder: C:\xampp\htdocs\laravel42-redminportal\assets , and the same problem is occurs for them.

**Comment by kongnir** [comment]
Hi @feryonline, try this and see if it works.
Find this file at C:\xampp\htdocs\laravel42-redminportal\bootstrap\paths.php

Edit these lines:

```
<?php

return array(

	'app' => __DIR__.'/../app',
	'public' => __DIR__.'/../public',
	'base' => __DIR__.'/..',
	'storage' => __DIR__.'/../app/storage',

);
```

To this:
*(Please also make sure the paths are correct, I'm assuming the installation path is C:\xampp\htdocs\laravel42-redminportal)*

```
<?php

return array(

	'app' => 'C:\xampp\htdocs\laravel42-redminportal\app',
	'public' => 'C:\xampp\htdocs\laravel42-redminportal\public',
	'base' => 'C:\xampp\htdocs\laravel42-redminportal',
	'storage' => 'C:\xampp\htdocs\laravel42-redminportal\app\storage',

);
```

**Comment by kongnir** [comment]
Hi @feryonline , I'm closing this issue. Please reopen it if you have further issue.
