### ISSUE TITLE
Errror when insert the first category

### ISSUE THREAD

**Issue by duccanh0022** [redooor/redminportal#41]
Hi, I have a problem when i add new category at first time. Plz help me!
Thanks :*

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`e-laravel_db`.`categories`, CONSTRAINT `categories_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)) (SQL: insert into `categories` (`name`, `short_description`, `long_description`, `active`, `order`, `options`, `category_id`, `updated_at`, `created_at`) values (Sport, This is sport category, <p>hi, i canh....</p>, 1, 0, {"name":null,"short_description":null,"long_description":null}, 0, 2015-01-05 02:36:15, 2015-01-05 02:36:15))

**Comment by kongnir** [comment]
Hi @duccanh0022, this should have been fixed at issue #37.
Are you using branch v1? If so you'll need to use the latest master.
Let me know if the problem still persists after syncing to latest master.

**Comment by duccanh0022** [comment]
Thanks, my problem resolved :+1:
