### ISSUE TITLE
Category Adding error

### ISSUE THREAD

**Issue by ulshamim** [redooor/redminportal#42]
I can't add a category. It shows an error. This is the error:
~~~
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`fancyshirt`.`categories`, CONSTRAINT `categories_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)) (SQL: insert into `categories` (`name`, `short_description`, `long_description`, `active`, `order`, `options`, `category_id`, `updated_at`, `created_at`) values (T-shirts, this is test category, <p>ghfjhjfghj</p>, 1, 0, {"name":null,"short_description":null,"long_description":null}, 0, 2015-01-08 09:45:30, 2015-01-08 09:45:30))
~~~

**Comment by kongnir** [comment]
Hi @ulshamim, this issue has already been resolved at issue #37.
Are you using branch v1 or master?

**Comment by ulshamim** [comment]
How can I see that? The changes log says it's Version 0.1.3. I followed this doc..
http://packalyst.com/packages/package/redooor/redminportal

**Comment by kongnir** [comment]
I see. We're planning to release the fix in version 0.1.4 on 10 Jan 2015. So it's still in the development branch.

In the mean time, you may get the latest of branch 0.1 by changing the following in file composer.json:

```
"require": {
    "redooor/redminportal": "0.1.*"
},
```

To this
```
"require": {
    "redooor/redminportal": "0.1.*@dev"
},
```

**Comment by kongnir** [comment]
Hi @ulshamim, v0.1.4 has been released. It consists of the fix for this issue. You may now change back to use the stable release in composer.json file.

```
"require": {
    "redooor/redminportal": "0.1.*"
},
```

**Comment by ulshamim** [comment]
Thanks.
