### ISSUE TITLE
Add a new menu item

### ISSUE THREAD

**Issue by ulshamim** [redooor/redminportal#46]
I can't add menu items. I have added array in config > menu.php file in both workbench and vendor file but nothing happen. Even I changed the path of existing menu items to check any changes but it doesn't work. It seems that the menu items are come from any other file location.

**Comment by kongnir** [comment]
Hi @ulshamim, did you publish the config?
You should then change the config file in 
root -> app -> config -> packages -> redooor -> redminportal -> menu.php

**Comment by ulshamim** [comment]
Oh yes it works. OK I want to know one little thing. If I would like to create any new module for back-end or like to change any file then in which folder I have to change so that after updating the package, my code will not overwrite : Workbench > redooor or Vendor > redooor.

**Comment by kongnir** [comment]
Hi @ulshamim, are you changing the core in Redminportal? Or just extending the functions?

If you're extending the functions, then you can do it anywhere. I would suggest extending the code directly in root -> app. Updates to the vendor folder will not affect the root folder. In short, never change any code within the vendor folder. When you run composer update, all the files will be overwritten.

If you're changing the core in Redminportal, then you may want to fork the source and only sync it in Workbench/redooor/redminportal. Please see README.md on instructions for Contributors. In short, do not use composer to install the package. Instead, use git to clone directly to Workbench/redooor/redminportal. If you merge this repository to your fork, if there's no conflict then it will merge successfully. If you don't mind sharing your code then may I suggest that you submit a "Pull Request" for us and we'll consider merging your change/suggestion into this repository. This way everyone can benefit from your contribution.

Cheers

**Comment by ulshamim** [comment]
Thanks a lot . I have no issue to share my code. Ok I will try in my local then submit a pull request. Thanks for my all newbie type question.
