### ISSUE TITLE
How to use for online shopping application? Question

### ISSUE THREAD

**Issue by logicalguy** [redooor/redminportal#47]
Hi,

I am creating a simple e-commerce application in Laravel.  The site will provide a list of about 50 products for people to buy online.  I am using this plugin to manage my list of products, and Laracart for shopping cart functionality.  I am wondering if this application supports saving orders.  What is the purpose of the Purchases screen?  And what are modules/memberships?

Sorry if these are really basic questions.

Thank you for your help.

**Comment by kongnir** [comment]
Hi @logicalguy 

Currently Redminportal doesn't support saving of orders for products yet.

"Purchases" is used to save orders for "Modules/Memberships". This is meant for digital products, we call them "Medias". To see this in active, try these steps:

1. Add 2 new Memberships (Name: Gold, Rank: 1 and Name: Silver, Rank: 2)
2. Add a new Category (Name: Cat1)
3. Add a new Media (Name: Media1, Category: Cat1)
4. Add a new Module (Name: Module1, Choose Category: Cat1, at the bottom of the creation page, under Media you should see Media1, and under Price List, you should see Gold and Silver)
5. Then add a new purchase (under "Module, Membership", you should now see "Module1, Gold" and "Module1, Silver)

Hope this answers your question.

**Comment by logicalguy** [comment]
Thank you.  Makes much more sense now.
