### ISSUE TITLE
Installation in laravel 5

### ISSUE THREAD

**Issue by ulshamim** [redooor/redminportal#65]
Today I installed laravel 5. What should I use comoser.json file and app provider array?

**Comment by kongnir** [comment]
Laravel 5 is not supported yet. I haven't explored it. It'll be great if you can help to report your findings here. Cheers

**Comment by kongnir** [comment]
Plan to support Laravel 5 in v0.2.0. See #54

**Comment by kongnir** [comment]
Support implemented in branch develop. Will upstream to master once all issues for v0.2.0 have been resolved.
