### ISSUE TITLE
Indidvual group for indvidual admin user

### ISSUE THREAD

**Issue by ulshamim** [redooor/redminportal#66]
How can i create different group for different admin user? I mean i have 2 admin user- admin1 and admin2 . Now I would like to add some groups for admin1 and some others for admin2. How can i achieve this?

**Comment by kongnir** [comment]
Hi @ulshamim ,

We're using Cartalyst/Sentry for user management, for the full documentation, you can visit https://cartalyst.com/manual/sentry/2.1

The Group model consists of 2 parts: name and permission.

If you look at the default groups created, you should see:
1. name: Admin, permission: admin = 1
2. name: User, permission: user = 1

For the Redminportal admin page, we're only allowing users with permission 'admin = 1' to access it, if you look at app/filters.php, look for Route::filter('auth.member') at line 69, we're checking if user has that permission with this code:

```
if ( $user->hasAccess('admin') )
```
Read: https://cartalyst.com/manual/sentry/2.1#hasaccess-permission

If you need multiple groups with permission 'admin = 1', you can simply create more groups with different names.

For example, I have 2 groups with names "Admin_Super" and "Admin_Moderator", I can then use the following codes to decide what to show them:

```
// Find the Administrator group
$admin_super = Sentry::findGroupByName('Admin_Super');
$admin_moderator = Sentry::findGroupByName('Admin_Moderator');

// Check if the user is in the administrator group
if ($user->inGroup($admin_super))
{
    // User is in Admin_Super group
}
else if ($user->inGroup($admin_moderator))
{
    // User is in Admin_Moderator group
}
else
{
    // User is not in both Administrator groups
}
```
Read: https://cartalyst.com/manual/sentry/2.1#ingroup-group

**Comment by kongnir** [comment]
I've added a Wiki page for this https://github.com/redooor/redminportal/wiki/2.-Group-Management

**Comment by ulshamim** [comment]
Ok. Is it possible to find find group by permission instead of name? Otherwise I can't show those particular groups which a particular admin user created.

**Comment by kongnir** [comment]
You can get all users with specific permission, see https://cartalyst.com/manual/sentry/2.1#find-all-the-users-with-access-to-a-permissions-s

```
// Feel free to pass a string for just one permission instead
$users = Sentry::findAllUsersWithAccess(array('admin', 'other'));
```

However, it's probably better to control specific permission using the **group name** instead. Otherwise the permission array gets too long and it's difficult to quickly search for them.

The group name is a string in the SQL column. The query will run faster than searching through the concatenated array of permissions.

**Comment by kongnir** [comment]
If you really need to get all groups with certain permission, then you need to use a custom query on the Group module instead of Sentry's Group, probably something like this (not tested):

```
Group::where('permissions', 'LIKE', '%admin%')->get();
```

**Comment by ulshamim** [comment]
Thank you very much :)
